--SUBCONSULTAS 
--SON CONSULTAS QUE NECESITAN DEL RESULTADO DE OTRA CONSULTA PARA PODER SER EJECUTADAS
--NO SON AUTÓNOMAS.
--NO IMPORTA EL NIVEL DE ANIDAMIENTO DE SUBCONSULTAS AUNQUE PUEDEN RALENTIZAR LAS RESPUESTAS
--GENERAN BLOQUEOS EN CONSULTAS SELECT, LO QUE TAMBIÉN RALENTIZAN LAS RESPUESTAS
--QUIERO VISULIZAR LOS DATOS DEL EMPLEADO QUE MÁS COBRA DE LA EMPRESA (EMP)
--DEBEMOS INTENTAR EVITARLAS EN LA  MEDIDA DE LA POSIBLE CON SELECT

select max(SALARIO) from EMP; --650000
select * from EMP where SALARIO=650000;

--SE EJECUTAN LAS DOS CONSULTAS A LA VEZ Y SE ANIDA EL RESULTADO DE UNA CONSULTA
--CON LA IGUALDAD DE LA RESPUESTA DE OTRA CONSULTA
--LAS SUBCONSULTAS VAN ENTRE PARENTESIS

select * from EMP where SALARIO = (select max(SALARIO) from EMP); --650000

--MOSTRAR LOS EMPLEADOS QUE TIENEN EL MISMO OFICIO QUE EL EMPLEADO "GIL"

select * from EMP;
select * from EMP where OFICIO = ( select OFICIO from EMP where APELLIDO = 'gil');

--Y QUE COBRAN MENOS QUE JIMENEZ

select * from EMP where OFICIO = ( select OFICIO from EMP where APELLIDO = 'gil')
and SALARIO < (select SALARIO from EMP where APELLIDO = 'jimenez');

-- MOSTRAR LOS EMPLEADOS QUE TIENEN EL MISMO OFICIO QUE GIL Y JIMENEZ

select * from EMP where OFICIO = ( select OFICIO from EMP where APELLIDO = 'gil' on APELLIDO = 'jimenez';---mal
--si muna subconsulta devuele más de un valor usamos el valor "in"
select * from EMP where OFICIO in ( select OFICIO from EMP where APELLIDO = 'gil' or APELLIDO = 'jimenez');

--POR SUPUESTO, PODEMOS UTILIZAR SUBCONSULTASPARA OTRAS TABLAS
--MOSTRAR EL APELLIDO Y OFICIO DE LOS DEP DE MADRID

select APELLIDO, OFICIO from EMP where DEPT_NO = (select DEPT_NO from DEPT where LOC = 'MADRID')

--SI TIENEN UN CAMPO COMÚN DEBEMOS HUIR DE LAS SUBCONSULTAS Y USAR UN JOIN
select EMP.APELLIDO, EMP.OFICIO
from EMP
inner join DEPT
on EMP.DEPT_NO = DEPT.DEPT_NO
where DEPT.LOC = 'MADRID';

--CONSULTAS UNION
--MUESTRAN EN UN MISMO CURSOR UN MISMO CONJUNTO DE RESULTADOS
--ESTAS CONSULTAS SE UTILIZAN COMO CONCEPTO, NO COMO RELACION
--DEBEMOS SEGUIR TRES NORMAS
    --1)LA PRIMERA CONSULTA ES LA JEFA
    --2)TODAS LAS CONSULTAS DEBEN TENER EL MISMO Nº DE COLUMNAS
    --3)TODAS LAS COLUMNAS DEBEN TENER EL MISMO TIPO  DE DATOS ENTRE SI
    --EN NUESTRA BBDD TENEMOS DATOS DE PERSONAS EN DIFERENTES TABLAS
    --EMP, PLANTILLA, DOCTOR...

select APELLIDO, OFICIO, SALARIO from EMP;
select APELLIDO, FUNCION, SALARIO from PLANTILLA;

select APELLIDO, OFICIO, SALARIO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA;

---SEGUIMOS ANIDANDO, SI CUMPLEN LAS CONDICIONES, AUNQUE NO TENGA SENTIDO SIGUE FUNCIONANDO
select APELLIDO, OFICIO, SALARIO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
union
select DNOMBRE, LOC, DEPT_NO from DEPT;

-----------SI QUEREMOS PONER ALIAS, A LA PRIMERA
select APELLIDO, OFICIO, SALARIO as SUELDO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA;

-----------NO FUNCIONA EN LAS SUCESIVAS
select APELLIDO, OFICIO, SALARIO from EMP
union
select APELLIDO, FUNCION, SALARIO AS SUELDO from PLANTILLA;

--POR SUPUESTO, PODEMOS ORDENAR SIN PROBLEMAS, SIEMPRE ES RECOMENDABLE ORDENARLO POR NUMERANDOS (order by 3)
select APELLIDO, OFICIO, SALARIO as SUELDO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
order by 3 desc;

-----
select APELLIDO, OFICIO, SALARIO as SUELDO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
order by SALARIO;

--si no se llaman igual los campos en todas las consultas no se pueden ordenar con el nombre

select APELLIDO, OFICIO, SALARIO as SUELDO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
order by OFICIO;

--PODEMOS FILTRAR LOS DATOS DE LA CONSULTA
--EJ: MOSTRAR LOS DATOS DE LAS PERSONAS QUE COBREN <300.000

select APELLIDO, OFICIO, SALARIO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
union
select APELLIDO, ESPECIALIDAD, SALARIO from DOCTOR
order by 1;

----ponemos el filtro del salario, ese filtro solo se aplica al último select
--si hubiera un enfermero que cobrara 400.000 me saldría en la consulta
select APELLIDO, OFICIO, SALARIO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
union
select APELLIDO, ESPECIALIDAD, SALARIO from DOCTOR
where SALARIO < 300000
order by 1;

--HAY QUE AÑADIR OTRO where
--CADA where ES INDEPENDIENTE AL UNION

select APELLIDO, OFICIO, SALARIO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
where SALARIO < 300000
union
select APELLIDO, ESPECIALIDAD, SALARIO from DOCTOR
where SALARIO < 300000
order by 1;
--CADA WHERE ES INDEPENDIENTE AL UNION

--UNION ELIMINA LOS RESULTADOS REPETIDOS
select APELLIDO, OFICIO from EMP
union 
select APELLIDO, OFICIO from EMP;

--SI QUEREMOS REPETIDOS DEBEMOS USAR UNION ALL

select APELLIDO, OFICIO from EMP
union all
select APELLIDO, OFICIO from EMP;

